# api-02-board

@baseurl = http://localhost:8080

### 001-create-board
POST {{baseurl}}/boards HTTP/1.1
Content-Type: application/json; charset=UTF-8
Accept: application/json

{
  "boardName": "FreeBoard"
}

### 002-get-boards
GET {{baseurl}}/boards HTTP/1.1
Content-Type: application/json; charset=UTF-8
Accept: application/json

{
  "boardName": "Board1",
  "page": 1,
  "size": 5
}

# TODO 페이지 옵션이 전혀 안먹힌다. 확인하자
