# server
server:
  port: 8080

# logging
logging:
  file:
    path: ./logs
  level:
    root: INFO
    io.vicevil4.slogging: DEBUG

spring:
  # spring h2 http://localhost:8080/h2-console 
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: