# server
server:
  port: 8080

# logging
logging:
  file:
    path: ./logs
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    io.vicevil4.slogging: DEBUG

spring:
  # spring h2 http://localhost:8080/h2-console 
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        validator:
          apply_to_ddl: false
